-- AlterTable
ALTER TABLE "problems" ADD COLUMN     "estimatedMinutes" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN     "likesCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "viewsCount" INTEGER NOT NULL DEFAULT 0;
